### PR TITLE
InsertAllObjects self recursion

### LINKED ISSUE #219: InsertAllObjects on android crashes v4.1.1
I just came up with a very interesting bug. Following code piece (InsertAllObjects) causing app crash:

```csharp
FetchNewArticles = ReactiveCommand.CreateAsyncTask (async priority => {
    if (State.Articles.Count > 0)
    {
        return await _newsService.GetArticlesAfterAsync(State.Articles[0], (Priority)priority);
    }
    else
    {
        return await _newsService.GetRemoteArticlesAsync((Priority)priority);
    }
});

FetchNewArticles.Subscribe (newArticles => {
    State.Articles.InsertRange(0, newArticles);

    var articlesKeyValue = newArticles.ToDictionary(x => "article-" + x.Id.ToString());
    _cache.InsertAllObjects (articlesKeyValue);
});
```

And there is no way to catch the bug on Xamarin's debugger. After I checked android logcat i found following interesting NullPointerException thrown:
```
W/Binder  (  848): java.lang.NullPointerException
W/Binder  (  848): 	at android.inputmethodservice.IInputMethodWrapper.setSessionEnabled(IInputMethodWrapper.java:280)
W/Binder  (  848): 	at com.android.internal.view.IInputMethod$Stub.onTransact(IInputMethod.java:129)
W/Binder  (  848): 	at android.os.Binder.execTransact(Binder.java:404)
W/Binder  (  848): 	at dalvik.system.NativeStart.run(Native Method)
D/AndroidRuntime( 7186): Shutting down VM
```

### PR DESCRIPTION
**Pull request by ncruces**
Should fix #219.

### CODE REVIEW

File: Akavache/Portable/JsonSerializationMixin.cs [hunk 1]
```diff
@@ -39,10 +39,10 @@ public static IObservable<Unit> InsertObject<T>(this IBlobCache This, string key
         /// <param name="keyValuePairs">The data to insert into the cache</param>
         /// <param name="absoluteExpiration">An optional expiration date.</param>
         /// <returns>A Future result representing the completion of the insert.</returns>
-        public static IObservable<Unit> InsertAllObjects<T>(this IBlobCache This, IDictionary<string, T> keyValuePairs, DateTimeOffset? absoluteExpiration = null)
+        public static IObservable<Unit> InsertObjects<T>(this IBlobCache This, IDictionary<string, T> keyValuePairs, DateTimeOffset? absoluteExpiration = null)
```
Comment (paulcbetts) [inline Akavache/Portable/JsonSerializationMixin.cs]: You can't rename a public method in a patch

**Comment by ncruces** [comment]
Sorry about that, it was a mistake.

`JsonSerializationMixin.InsertAllObjects` should remain as is, but it should delegate to `BulkOperationsMixin.InsertObjects` iff `This` implements `IObjectBlobCache`.

Going down this rabbit hole I also noted that `BulkOperationsMixin.Insert` and `BulkOperationsMixin.InsertObjects` don't pass down the `absoluteExpiration`.

**Comment by paulcbetts** [comment]
:+1:
